### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by K-OMA** [JiminGod/WirelessNetwork#2]
![2 1](https://github.com/JiminGod/WirelessNetwork/assets/132823624/5dcbc9a5-7a63-45d5-8afe-9a6f47d9d6c9)
![1 1](https://github.com/JiminGod/WirelessNetwork/assets/132823624/8ac903ec-a103-4092-b79d-4049b3f98043)

DB는 6개의 테이블으로 구성됩니다.

1. 학생정보테이블 / student
컬럼 소개는 위 사진으로 대체하겠습니다. 학생정보가 기록될 테이블으로 학생사진은 좀 알아본 이후에 컬럼을 추가할 예정입니다.

2. 교수정보테이블 / prof
교수정보가 기록될 테이블으로 만약에 앱으로 제작한다면 교번을 통해서 로그인 이후에 강의정보테이블과 연계해 교수의 강의목록을 보여준다면 좋겠다 생각합니다.

3. 강의정보테이블 / class
강의정보가 기록될 테이블으로 단순히 강의명으로 기록하기는 반마다, 시간별마다 강의가 존재하므로 영문자숫자 혼합의 고유한 강의코드를 기본 키로 기록할 예정입니다.

4. 출석정보테이블 / attend
출석정보가 기록될 테이블으로 최초에 교번과 강의 코드를 설정해두면 좋을 것 같습니다.

얼굴 인식을 통해서 학생얼굴을 인식해 학번을 파악.

이후에 강의수강학생테이블과 연계해 수강인원이 맞는지 판별.

또, 강의환경설전테이블과 연계해 지각 시간을 등록해두면 출석 시간과 비교해 출석 코드를 등록합니다.

추가로 출석 코드는 결석, 지각, 출석 만 가능하도록 제약조건을 구성할 계획입니다.

5. 강의환경설정테이블 / class_setup
강의의 지각시간을 기록할 테이블이며 이전 상태를 기억하여서 추후에 변경사항이 없으면 이 컬럼을 기준으로 출석코드를 등록합니다.

6. 강의수강학생테이블
수강학생을 판별할 테이블으로 강의를 등록했으면 필수적으로 이 테이블에도 최소 정원이 등록되도록 만들고 싶습니다만... 방법을 몰라서 알아가는 중입니다.

일단은 수강인원을 Ui 표시해주고 등록되있지 않은 학생은 무시하도록 설계하면은 좋을 것 같습니다.

이상입니다.

**Comment by FireChicks** [comment]
**지문인식기능의 추가와 이미지, 모델 파일의 DB 추가로 ERD도 조금 수정됐습니다.**

1.  student 테이블의 stu_pic(대표 이미지), stu_finger_dat(지문 템플릿) 컬럼 추가
2. class 테이블의 class_model 컬럼 추가
3. image 테이블 추가 <- 학습되기전의 사람별 100장의 이미지가 저장되어 있는 테이블


**image 테이블**
*img_id : 이미지파일의 기본 키
*stu_id : student테이블의 외래 키
*img: 이미지가 저장되어있는 컬럼

->class_stu에서 수강하는 학생들의 학번 리스트를 가져와서 이 학번 리스트를 바탕으로 학생당 100장의 이미지를 image 테이블에서 꺼내서 학습시켜 yml파일로 만들어 class_model에 추가하는 기능을 추가 예정입니다. 

[Dump20231128.zip](https://github.com/JiminGod/WirelessNetwork/files/13478377/Dump20231128.zip)
수정된 sql 파일입니다.
